linters-settings:
  lll:
    line-length: 120
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cloudnative-pg/cnpg-i-hello-world)
      - blank
      - dot
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 3

linters:
  enable-all: true
  disable:
    - depguard
    - execinquery
    - exhaustive
    - exhaustruct
    - err113
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godot
    - gomnd
    - ireturn
    - varnamelen
    - wrapcheck
    - wsl

run:
  timeout: 10m
