apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  plugins:
  - name: cnpg-i-hello-world.cloudnative-pg.io
    parameters:
      labels: |
        {
          "first-label": "first-label-value",
          "second-label": "second-label-value"
        }
      annotations: |
        {
          "first-annotation": "first-annotation-value"
        }

  storage:
    size: 1Gi
