apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-server
  namespace: cnpg-system
spec:
  secretName: helloworld-server-tls
  commonName: "hello-world"
  dnsNames:
    - hello-world

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io